class WindowManager:
    def __init__(self) -> None: ...
    def start(self, debug: bool = False) -> None: ...
    def get_port(self) -> int: ...
    def send_html(self, html: str, title: str = "") -> None: ...
