# Adapted from: https://github.com/tauri-apps/tauri/issues/1355#issuecomment-896434917
name: Pip

on: workflow_dispatch

jobs:
  manylinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        #python-version: ["3.7", "3.8", "3.9", "3.10"]
        target: [x86_64]
        processor: [ x86_64 ]
        #target: [x86_64, i686]  
    container:
      image: quay.io/pypa/manylinux2014_${{ matrix.processor }}
      options: --user root  
    steps:
      - name : Setup sudo apt installs for ubuntu-latest
        run: |
          yum install -y \
              # notice I'm using an old version of webkit. It works!
              webkitgtk4-devel \
              openssl-devel \
              curl \
              wget \
              squashfs-tools \
              gcc \
              gcc-c++ \
              make \
              file \
              librsvg2-devel

      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release -o dist --find-interpreter
      - name: Install build wheel
        if: matrix.target == 'x86_64'
        run: |
          pip install --force-reinstall dist/pywry*.whl
          cd ~ && python -X faulthandler -c 'import pywry'
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist